formatting:
 MaxLineLength:
    active: true
    maxLineLength: 120
    ignoreBackTickedIdentifier: false
complexity:
 TooManyFunctions:
    active: true
    max: 2
    excludedFunctions: ['equals']
    excludeLabeled: false
    excludeReturnFromLambda: true
    excludeGuardClauses: false


    
