style:
 MaxLineLength:
    active: true
    maxLineLength: 120
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: false
    excludeRawStrings: true
complexity:
 TooManyFunctions:
    active: true
    threshold: 100
    excludes: ['**/test/**', '**/generated/**']



    
