name: Static Analyser
on:
  push:
    branches: [ "main" ]

jobs:
  detekt:
    name: detekt
    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v2

      - name: "run"
        uses: natiginfo/action-detekt-all@1.23.6
        # from: https://github.com/natiginfo/action-detekt-all
        with:
          args:  --config .github/detekt-config.yml

